"""Kernel event type constants."""

ProjectCreated = "ProjectCreated"
PhaseEntered = "PhaseEntered"
PhaseStarted = "PhaseStarted"
PhaseCompleted = "PhaseCompleted"
GateEvaluated = "GateEvaluated"
GatePassed = "GatePassed"
GateRejected = "GateRejected"
ArtifactValidated = "ArtifactValidated"
ArtifactCreated = "ArtifactCreated"
ValidationFailed = "ValidationFailed"
ReworkStarted = "ReworkStarted"
ReworkCompleted = "ReworkCompleted"
TransitionBlocked = "TransitionBlocked"
ProjectBlocked = "ProjectBlocked"
ProjectReleased = "ProjectReleased"
ProjectClosed = "ProjectClosed"
AgentInvoked = "AgentInvoked"
AgentInvocationFailed = "AgentInvocationFailed"
StateSaved = "StateSaved"
WorkflowVersionMismatch = "WorkflowVersionMismatch"
PipelinePaused = "PipelinePaused"
PipelineResumed = "PipelineResumed"
PipelineCompleted = "PipelineCompleted"
