"""Source control provider abstraction."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from source_control.types import CommitResult, RepositoryContext, RepositoryStatus


class ISourceControlProvider(Protocol):
    """Provider interface — no package executes Git directly outside providers."""

    provider_id: str

    def is_available(self) -> bool: ...

    def status(self, repo_root: Path) -> RepositoryStatus: ...

    def diff(self, repo_root: Path, *, staged: bool = False, path: str | None = None) -> str: ...

    def log(self, repo_root: Path, limit: int = 20) -> list[dict]: ...

    def branches(self, repo_root: Path) -> list[str]: ...

    def current_branch(self, repo_root: Path) -> str | None: ...

    def checkout(self, repo_root: Path, branch: str) -> None: ...

    def stage(self, repo_root: Path, paths: list[str] | None = None) -> list[str]: ...

    def unstage(self, repo_root: Path, paths: list[str] | None = None) -> list[str]: ...

    def commit(self, repo_root: Path, message: str) -> CommitResult: ...

    def push(self, repo_root: Path, remote: str = "origin", branch: str | None = None) -> dict: ...

    def tag(self, repo_root: Path, name: str, message: str = "", annotated: bool = True) -> dict: ...

    def remote_url(self, repo_root: Path) -> str | None: ...

    def init_repo(self, repo_root: Path) -> None: ...
